### ISSUE TITLE
运行 python csv_to_MongoDB.py 出错

### ISSUE THREAD

**Issue by gaorufeng** [Chandlercjy/OnePy#1]
您好,非常感谢您的代码,我对py还不熟悉,类这关卡一直没过...  我运行案例里面的csv_to_MongoDB.py 报错

C:\OnePy\examples>c:\py36\python csv_to_MongoDB.py
Traceback (most recent call last):
  File "csv_to_MongoDB.py", line 3, in <module>
    from OnePy.tools.to_Mongodb import Forex_CSV_to_MongoDB
  File "c:\py36\lib\site-packages\OnePy\tools\to_Mongodb.py", line 11, in <module>
    from ..broker import oanda
ModuleNotFoundError: No module named 'OnePy.broker'

**Comment by Chandlercjy** [comment]
不好意思刚看到。
你应该是用pip安装的吧，我出现这个错误的原因是我自己在调试开发oanda的api，不小心和这个开源版本的OnePy混合了。

现在我已经将pip版本更新为1.3.11，你重新upgrade一下就行。

或者直接在github下载代码zip到本地运行即可。

你试试行不，如果有错误的话可以再提：）
