### ISSUE TITLE
signals.py 里面的 dataclasses模块

### ISSUE THREAD

**Issue by jshchengcong** [Chandlercjy/OnePy#2]
你好，我已经pip安装了dataclasses模块了，但是仍然显示

ModuleNotFoundError: No module named 'dataclasses'
Process finished with exit code 1

请问这个如何解决。

谢谢！

**Comment by Chandlercjy** [comment]
我估计你会不会安装错了，按道理pip安装好后应该就能够运行。

检查一下你电脑是不是安装了多个版本的python，dataclasses是否安装到运行OnePy的Python版本。

顺带一提，dataclasses会再Python 3.7成为标准库，详见
https://zhuanlan.zhihu.com/p/34963159
