### ISSUE TITLE
base_reader.py

### ISSUE THREAD

**Issue by grantfang** [Chandlercjy/OnePy#3]
你好！
想请教一下，在你的base_reader.py中load方法，从csv或者mongodb读取之后最终返回的是什么内容？是dataframe？dict？

**Comment by Chandlercjy** [comment]
读取之后返回的是迭代器，每一条迭代器内容为dict，内容类似：
OrderedDict([('date', '2018-01-02'), ('open', 13.35), ('close', 13.7), ('high', 13.93), ('low', 13.32), ('volume', 2081592.0)])

目前没有添加tick模式，全部是ohlc。
注意date、open、high、low、close、volume均为小写。
