### ISSUE TITLE
每支股票新建一个连接是否合理？

### ISSUE THREAD

**Issue by lichang1019** [Chandlercjy/OnePy#6]
如果全A选股，需要3000多个mongodb连接？

**Comment by Chandlercjy** [comment]
感谢提出，已修复：）

**Comment by lichang1019** [comment]
1、这样写好像没解决问题。。新建一个reader还是会新建一个连接，直接写env里好了，或者一次读到内存里然后再迭代器。
2、回测时间应该按照calendar时间，这样有bug。
3、没考虑复权。
4、感谢分享！

**Comment by Chandlercjy** [comment]
1. 啊确实要加到env会比较好！这点我确实没想到哈。因为之前我运行时，回测4000只股票会出现数据库崩溃。按目前这种改法就没啥问题，峰值连接数为reader数。但是按你放到env的做法能直接减少至1。

2. 回测calendar模块我在专栏最新一篇文章
https://zhuanlan.zhihu.com/p/41108459
也已经提到了，确实要写calendar模块才行。本框架主要是学习交流之用，希望能提供写框架思路之后再根据自己需求自己改进哈，可以的话也可以pull request～ 我最近比较忙暂时没考虑更新到框架中😂

3. 框架只提供了最通用的模块，其他需求可以根据自己需求写出。

4. 感谢关注！有兴趣可以知乎私信我wechat进一步交流🌝

**Comment by Chandlercjy** [comment]
Calendar模块已添加到2.5版本中。
